import type {StrategyGrid} from "@/models/strategy/determineCorrectAction.ts";

export const basicStrategyH17: StrategyGrid = {
      id: 'basicStrategyH17',
      name: 'Basic Strategy H17',
     '2_2': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_3': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_4': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_5': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_6': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_7': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_8': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_9': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
    '2_10': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '2_1': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],

     '3_2': [{action: 'Hit'}],
     '3_3': [{action: 'Hit'}],
     '3_4': [{action: 'Hit'}],
     '3_5': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '3_6': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '3_7': [{action: 'Hit'}],
     '3_8': [{action: 'Hit'}],
     '3_9': [{action: 'Hit'}],
    '3_10': [{action: 'Hit'}],
     '3_1': [{action: 'Hit'}],

     '4_2': [{canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '4_3': [{canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '4_4': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '4_5': [{isSoft: true, canDouble: true, action: 'Double'}, {canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '4_6': [{isSoft: true, canDouble: true, action: 'Double'}, {canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '4_7': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '4_8': [{action: 'Hit'}],
     '4_9': [{action: 'Hit'}],
    '4_10': [{action: 'Hit'}],
     '4_1': [{action: 'Hit'}],

     '5_2': [{action: 'Hit'}],
     '5_3': [{action: 'Hit'}],
     '5_4': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '5_5': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '5_6': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '5_7': [{action: 'Hit'}],
     '5_8': [{action: 'Hit'}],
     '5_9': [{action: 'Hit'}],
    '5_10': [{action: 'Hit'}],
     '5_1': [{action: 'Hit'}],

     '6_2': [{canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '6_3': [{canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '6_4': [{isSoft: true, canDouble: true, action: 'Double'}, {canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '6_5': [{isSoft: true, canDouble: true, action: 'Double'}, {canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '6_6': [{isSoft: true, canDouble: true, action: 'Double'}, {canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '6_7': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '6_8': [{action: 'Hit'}],
     '6_9': [{action: 'Hit'}],
    '6_10': [{action: 'Hit'}],
     '6_1': [{action: 'Hit'}],

     '7_2': [{action: 'Hit'}],
     '7_3': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '7_4': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '7_5': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '7_6': [{isSoft: true, canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '7_7': [{action: 'Hit'}],
     '7_8': [{action: 'Hit'}],
     '7_9': [{action: 'Hit'}],
    '7_10': [{action: 'Hit'}],
     '7_1': [{action: 'Hit'}],

     '8_2': [{isSoft: true, canDouble: true, action: 'Double'}, {isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '8_3': [{isSoft: true, canDouble: true, action: 'Double'}, {isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '8_4': [{isSoft: true, canDouble: true, action: 'Double'}, {isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '8_5': [{isSoft: true, canDouble: true, action: 'Double'}, {isSoft: true, action: 'Stand'}, {canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '8_6': [{isSoft: true, canDouble: true, action: 'Double'}, {isSoft: true, action: 'Stand'}, {canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '8_7': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '8_8': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '8_9': [{action: 'Hit'}],
    '8_10': [{action: 'Hit'}],
     '8_1': [{action: 'Hit'}],

     '9_2': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '9_3': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '9_4': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '9_5': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '9_6': [{isSoft: true, canDouble: true, action: 'Double'}, {isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '9_7': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '9_8': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '9_9': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
    '9_10': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '9_1': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],

     '10_2': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_3': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_4': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_5': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_6': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_7': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_8': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '10_9': [{isSoft: true, action: 'Stand'}, {canDouble: true, action: 'Double'}, {action: 'Hit'}],
    '10_10': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],
     '10_1': [{isSoft: true, action: 'Stand'}, {action: 'Hit'}],

     '11_2': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_3': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_4': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_5': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_6': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_7': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_8': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_9': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
    '11_10': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],
     '11_1': [{canDouble: true, action: 'Double'}, {action: 'Hit'}],

     '12_2': [{canSplit: true, DAS: true, action: 'Split'}, {action: 'Hit'}],
     '12_3': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '12_4': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '12_5': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '12_6': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '12_7': [{action: 'Hit'}],
     '12_8': [{action: 'Hit'}],
     '12_9': [{action: 'Hit'}],
    '12_10': [{action: 'Hit'}],
     '12_1': [{action: 'Hit'}],

     '13_2': [{action: 'Stand'}],
     '13_3': [{action: 'Stand'}],
     '13_4': [{action: 'Stand'}],
     '13_5': [{action: 'Stand'}],
     '13_6': [{action: 'Stand'}],
     '13_7': [{action: 'Hit'}],
     '13_8': [{action: 'Hit'}],
     '13_9': [{action: 'Hit'}],
    '13_10': [{action: 'Hit'}],
     '13_1': [{action: 'Hit'}],

     '14_2': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '14_3': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '14_4': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '14_5': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '14_6': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '14_7': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '14_8': [{action: 'Hit'}],
     '14_9': [{action: 'Hit'}],
    '14_10': [{action: 'Hit'}],
     '14_1': [{action: 'Hit'}],

     '15_2': [{action: 'Stand'}],
     '15_3': [{action: 'Stand'}],
     '15_4': [{action: 'Stand'}],
     '15_5': [{action: 'Stand'}],
     '15_6': [{action: 'Stand'}],
     '15_7': [{action: 'Hit'}],
     '15_8': [{action: 'Hit'}],
     '15_9': [{action: 'Hit'}],
    '15_10': [{canSurrender: true, action: 'Surrender'}, {action: 'Hit'}],
     '15_1': [{canSurrender: true, action: 'Surrender'}, {action: 'Hit'}],

     '16_2': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '16_3': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '16_4': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '16_5': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '16_6': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '16_7': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '16_8': [{canSplit: true, action: 'Split'}, {action: 'Hit'}],
     '16_9': [{canSplit: true, action: 'Split'}, {canSurrender: true, action: 'Surrender'}, {action: 'Hit'}],
    '16_10': [{canSplit: true, action: 'Split'}, {canSurrender: true, action: 'Surrender'}, {action: 'Hit'}],
     '16_1': [{canSurrender: true, action: 'Surrender'}, {canSplit: true, action: 'Split'}, {action: 'Hit'}],

     '17_2': [{action: 'Stand'}],
     '17_3': [{action: 'Stand'}],
     '17_4': [{action: 'Stand'}],
     '17_5': [{action: 'Stand'}],
     '17_6': [{action: 'Stand'}],
     '17_7': [{action: 'Stand'}],
     '17_8': [{action: 'Stand'}],
     '17_9': [{action: 'Stand'}],
    '17_10': [{action: 'Stand'}],
     '17_1': [{canSurrender: true, action: 'Surrender'}, {action: 'Stand'}],

     '18_2': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '18_3': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '18_4': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '18_5': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '18_6': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '18_7': [{action: 'Stand'}],
     '18_8': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
     '18_9': [{canSplit: true, action: 'Split'}, {action: 'Stand'}],
    '18_10': [{action: 'Stand'}],
     '18_1': [{action: 'Stand'}],

     '19_2': [{action: 'Stand'}],
     '19_3': [{action: 'Stand'}],
     '19_4': [{action: 'Stand'}],
     '19_5': [{action: 'Stand'}],
     '19_6': [{action: 'Stand'}],
     '19_7': [{action: 'Stand'}],
     '19_8': [{action: 'Stand'}],
     '19_9': [{action: 'Stand'}],
    '19_10': [{action: 'Stand'}],
     '19_1': [{action: 'Stand'}],

     '20_2': [{action: 'Stand'}],
     '20_3': [{action: 'Stand'}],
     '20_4': [{action: 'Stand'}],
     '20_5': [{action: 'Stand'}],
     '20_6': [{action: 'Stand'}],
     '20_7': [{action: 'Stand'}],
     '20_8': [{action: 'Stand'}],
     '20_9': [{action: 'Stand'}],
    '20_10': [{action: 'Stand'}],
     '20_1': [{action: 'Stand'}],
}
